/**
 * One-time data migration: legacy Flask SQLite -> Cloudflare D1.
 *
 * Reads legacy-flask/bookings.db (via Node's built-in node:sqlite, Node 22.5+)
 * and the gallery photos in legacy-flask/static/uploads, and emits a single
 * scripts/seed-data.sql containing all rows + the images (base64) for D1.
 *
 * Usage:
 *   node scripts/migrate-data.mjs
 *   npx wrangler d1 execute lucid --remote --file=scripts/seed-data.sql   # production
 *   # (use --local instead of --remote for local dev)
 */
import { DatabaseSync } from "node:sqlite";
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dbPath = join(root, "legacy-flask", "bookings.db");
const uploadsDir = join(root, "legacy-flask", "static", "uploads");

if (!existsSync(dbPath)) {
  console.error(`Cannot find ${dbPath}`);
  process.exit(1);
}

const db = new DatabaseSync(dbPath);

const sqlVal = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number" || typeof v === "bigint") return String(v);
  return "'" + String(v).replace(/'/g, "''") + "'";
};

function dumpTable(table, { replace = false } = {}) {
  let rows;
  try {
    rows = db.prepare(`SELECT * FROM ${table}`).all();
  } catch {
    return "";
  }
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const verb = replace ? "INSERT OR REPLACE" : "INSERT OR IGNORE";
  const lines = rows.map(
    (r) => `${verb} INTO ${table} (${cols.join(", ")}) VALUES (${cols.map((c) => sqlVal(r[c])).join(", ")});`,
  );
  return `-- ${table} (${rows.length} rows)\n${lines.join("\n")}\n\n`;
}

const MIME = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".gif": "image/gif",
};

let sql = "-- Generated by scripts/migrate-data.mjs\nPRAGMA defer_foreign_keys = true;\n\n";
sql += dumpTable("bookings");
sql += dumpTable("customers");
sql += dumpTable("availability");
sql += dumpTable("settings", { replace: true }); // override seeded defaults with real values
sql += dumpTable("gallery");
sql += dumpTable("reviews");

// Gallery photos -> images table (base64 in D1)
if (existsSync(uploadsDir)) {
  const files = readdirSync(uploadsDir).filter((f) => !f.startsWith("."));
  if (files.length) {
    sql += `-- images (${files.length} photos)\n`;
    for (const f of files) {
      const ext = f.slice(f.lastIndexOf(".")).toLowerCase();
      const ct = MIME[ext] || "application/octet-stream";
      const b64 = readFileSync(join(uploadsDir, f)).toString("base64");
      sql += `INSERT OR REPLACE INTO images (key, content_type, data) VALUES ('${f}', '${ct}', '${b64}');\n`;
    }
    sql += "\n";
    console.log(`Embedded ${files.length} photo(s) into the seed.`);
  }
}

const seedPath = join(root, "scripts", "seed-data.sql");
writeFileSync(seedPath, sql);
db.close();

console.log(`Wrote ${seedPath}`);
console.log("\nNext:");
console.log("  npx wrangler d1 execute lucid --remote --file=scripts/seed-data.sql   # production");
console.log("  npx wrangler d1 execute lucid --local  --file=scripts/seed-data.sql   # local dev");
