/**
 * One-time data migration: legacy Flask SQLite -> Cloudflare D1 + R2.
 *
 * Reads legacy-flask/bookings.db (via Node's built-in node:sqlite, Node 22.5+)
 * and emits:
 *   - scripts/seed-data.sql   : INSERTs for D1
 *   - scripts/upload-r2.sh    : wrangler commands to upload gallery photos to R2
 *
 * Usage:
 *   node scripts/migrate-data.mjs
 *   npx wrangler d1 execute lucid --remote --file=scripts/seed-data.sql
 *   bash scripts/upload-r2.sh
 */
import { DatabaseSync } from "node:sqlite";
import { readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dbPath = join(root, "legacy-flask", "bookings.db");
const uploadsDir = join(root, "legacy-flask", "static", "uploads");

if (!existsSync(dbPath)) {
  console.error(`Cannot find ${dbPath}`);
  process.exit(1);
}

const db = new DatabaseSync(dbPath);

const sqlVal = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  if (typeof v === "bigint") return String(v);
  return "'" + String(v).replace(/'/g, "''") + "'";
};

function dumpTable(table, { replace = false } = {}) {
  let rows;
  try {
    rows = db.prepare(`SELECT * FROM ${table}`).all();
  } catch {
    return "";
  }
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const verb = replace ? "INSERT OR REPLACE" : "INSERT OR IGNORE";
  const lines = rows.map(
    (r) => `${verb} INTO ${table} (${cols.join(", ")}) VALUES (${cols.map((c) => sqlVal(r[c])).join(", ")});`,
  );
  return `-- ${table} (${rows.length} rows)\n${lines.join("\n")}\n\n`;
}

let sql = "-- Generated by scripts/migrate-data.mjs\nPRAGMA defer_foreign_keys = true;\n\n";
sql += dumpTable("bookings");
sql += dumpTable("customers");
sql += dumpTable("availability");
sql += dumpTable("settings", { replace: true }); // override seeded defaults with real values
sql += dumpTable("gallery");
sql += dumpTable("reviews");

const seedPath = join(root, "scripts", "seed-data.sql");
writeFileSync(seedPath, sql);
console.log(`Wrote ${seedPath}`);

// R2 upload script for gallery photos
let sh = "#!/usr/bin/env bash\nset -e\n";
if (existsSync(uploadsDir)) {
  const mime = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".gif": "image/gif",
  };
  const files = readdirSync(uploadsDir).filter((f) => !f.startsWith("."));
  for (const f of files) {
    const ext = f.slice(f.lastIndexOf(".")).toLowerCase();
    const ct = mime[ext] || "application/octet-stream";
    sh += `npx wrangler r2 object put "lucid-gallery/${f}" --file="legacy-flask/static/uploads/${f}" --content-type="${ct}" --remote\n`;
  }
  console.log(`Found ${files.length} upload(s) to push to R2.`);
}
const shPath = join(root, "scripts", "upload-r2.sh");
writeFileSync(shPath, sh);
console.log(`Wrote ${shPath}`);

db.close();
console.log("\nNext:");
console.log("  npx wrangler d1 execute lucid --remote --file=scripts/seed-data.sql");
console.log("  bash scripts/upload-r2.sh");
